ShoppingCart/Controllers/ShoppingController.cs
using ShoppingCart.Models;
using ShoppingCart.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCart.Controllers
{
    public class ShoppingController : Controller
    {
        private ECartDBEntities objECartDbEntities;
        List<ShoppingCartViewModel> listOfShoppingCartModels;
        public ShoppingController()
        {
            objECartDbEntities = new ECartDBEntities();
            listOfShoppingCartModels = new List<ShoppingCartViewModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> listofShoppingViewModels = (from objItem in objECartDbEntities.Items join objCat in objECartDbEntities.Categories
                on objItem.CategoryID equals objCat.CategoryID
                select new ShoppingViewModel() 
                {
                    ImagePath = objItem.ImagePath,
                    ItemName = objItem.ItemName,
                    Description = objItem.Description,
                    ItemPrice = objItem.ItemPrice,
                    ItemID = objItem.ItemID,
                    Category = objCat.CategoryName,
                    ItemCode = objItem.ItemCode
                }
                ).ToList();
            return View(listofShoppingViewModels);
        }

        [HttpPost]
        public JsonResult Index(string itemID)
        {
            ShoppingCartViewModel objShoppingViewModel = new ShoppingCartViewModel();
            Item objItem = objECartDbEntities.Items.Single(model => model.ItemID.ToString() == itemID);

            if(Session["CartCounter"] != null)
            {
                listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartViewModel>;
            }

            if(listOfShoppingCartModels.Any(model => model.ItemID == itemID))
            {
                objShoppingViewModel = listOfShoppingCartModels.Single(model => model.ItemID == itemID);
                objShoppingViewModel.Quantity = objShoppingViewModel.Quantity + 1;
                objShoppingViewModel.Total = objShoppingViewModel.Quantity * objShoppingViewModel.UnitPrice;
            }

            else
            {
                objShoppingViewModel.ItemID = itemID;
                objShoppingViewModel.ImagePath = objItem.ImagePath;
                objShoppingViewModel.ItemName = objItem.ItemName;
                objShoppingViewModel.Quantity = 1;
                objShoppingViewModel.Total = objItem.ItemPrice;
                objShoppingViewModel.UnitPrice = objItem.ItemPrice;
                listOfShoppingCartModels.Add(objShoppingViewModel);
                
            }

            Session["CartCounter"] = listOfShoppingCartModels.Count;
            Session["CartItem"] = listOfShoppingCartModels;


            return Json(new {Success = true, Counter = listOfShoppingCartModels.Count}, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult ShoppingCart()
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartViewModel>;
            return View(listOfShoppingCartModels);
        }

        [HttpPost]
        public ActionResult AddOrder()
        {
            int OrderID = 0;
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartViewModel>;
            Order orderObj = new Order()
            {
                OrderDate = DateTime.Now,
                OrderNumber = String.Format("{0:ddmmyyyyHHmmss}", DateTime.Now)
            };
            objECartDbEntities.Orders.Add(orderObj);
            objECartDbEntities.SaveChanges();

            OrderID = orderObj.OrderID;

            foreach(var item in listOfShoppingCartModels)
            {
                OrderDetail objOrderDetail = new OrderDetail();
                objOrderDetail.Total = item.Total;
                objOrderDetail.ItemID = item.ItemID;
                objOrderDetail.OrderID = OrderID;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.UnitPrice = item.UnitPrice;
                objECartDbEntities.OrderDetails.Add(objOrderDetail);
                objECartDbEntities.SaveChanges();
            }

            Session["CartItem"] = null;
            Session["CartCounter"] = null;
            return RedirectToAction("Index");
        }
    }
}

ShoppingCart/Views/Shopping/Index.cshtml
@model IEnumerable<ShoppingCart.ViewModel.ShoppingViewModel>
@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">
    function AddToCart(item) {
        var itemId = $(item).attr("itemId");
        var formData = new FormData();
        formData.append("ItemId", itemId);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: formData,
            url: '/Shopping/Index',
            success: function (data) {
                if (data.Success) {
                    $("#cartItem").text("Cart(" + data.Counter + ")");
                }
            },
            error: function () {
                alert("There has been an error adding to shopping cart")
            }
        });
    }
</script>

<div class="container">
    <h2 class="text-center">Product List</h2>
    @foreach(var item in Model)
    {
        <div class="col-md-4" style="border: 2px solid black">
            <div style="text-align: center; border-bottom: 1px solid maroon">
                <h4>@item.ItemName</h4>
            </div>
            <div>
                <div class="col-md-8">
                    <img src="@Url.Content(@item.ImagePath)" width="150px" height="150px" />
                </div>
                <div class="col-md-4" style="text-align: left">
                    <p style="font-weight: bold">@item.Description</p>
                </div>
            </div>

            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid maroon; padding: 2px">
                <p style="font-weight: bold">@item.ItemPrice.ToString("#,##0.00 AUD")</p>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid maroon; padding: 2px">
                <input type="button" name="AddToCart" value="Add to Cart" class="btn btn-primary"itemid="@item.ItemID" id="btnAddToCart" onclick="AddToCart(this)" />
            </div>
        </div>
    }
</div>

ShoppingCart/Views/Shopping/ShoppingCart.cshtml
@model IEnumerable<ShoppingCart.ViewModel.ShoppingCartViewModel>
@{
    ViewBag.Title = "ShoppingCart";
    decimal TotalAmount = 0.00M;
}



<h2>ShoppingCart</h2>
@using (Html.BeginForm("AddOrder", "Shopping", FormMethod.Post))
{
<table class="table-condensed" style="width: 100%">
    @foreach (var item in Model)
    {
        TotalAmount += item.Total;
        <tr>
            <td>
                <img src="@Url.Content(item.ImagePath)" height="50px" width="50px" class="img-rounded" />
            </td>
            <td>
                @item.ItemName
            </td>
            <td style="text-align: right">
                @item.Quantity.ToString("#,##0")
            </td>
            <td style="text-align: right">
                @item.UnitPrice.ToString("#,##0.00")
            </td>
            <td style="text-align: right">
                @item.Total.ToString("#,##0.00")
            </td>
        </tr>
    }

    <tr style="border-top: 2px solid blue">
        <td colspan="4" style="text-align: right">
            <h3>Total Amount</h3>
        </td>
        <td style="text-align: right">
            <h3>@TotalAmount.ToString("#,##0.00")</h3>
        </td>
    </tr>

    <tr style="text-align: right">
        <td colspan="5">
            <input type="submit" value="Save" name="Save" class="btn btn-primary" id="SaveOrder" />
        </td>
    </tr>

    <tr style="text-align: center">
        <td colspan="5">
            @Html.ActionLink("Back to Shopping", "Index", "Shopping")
        </td>
    </tr>
</table>
}